# environments allow version pinning via env or CLI
environments:
  default:
    values:
      - version: 5.51.6
# Helmfile for ArgoCD deployment

repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
  - name: argocd
    namespace: argocd
    createNamespace: true
    chart: argo/argo-cd
    version: {{ .Values.version }}
    values:
      - server:
          service:
            type: LoadBalancer
        configs:
          params:
            server.insecure: true
